final_project/account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from .views import CheckAppointmentsView, CreateProfileView, DetailProfileView, UpdateProfileView, ConfirmEmailView, \
    ResendConfirmationMail
app_name = 'account'

urlpatterns = [
    path('register/', CreateProfileView.as_view(), name='registration'),
    path('password_change_form/', auth_views.PasswordChangeView.as_view(template_name='account/password_change_form.html', success_url=reverse_lazy('account:password-change-done')), name='password-change'),
    path('password_change_done/', auth_views.PasswordChangeDoneView.as_view(template_name='account/password_change_done.html'), name='password-change-done'),
    path('profile-detail/<int:pk>/', DetailProfileView.as_view(), name='profile_detail'),
    path('profile-edit/<int:pk>/', UpdateProfileView.as_view(), name='profile_edit'),
    path('appointment-profile/<int:pk>/', CheckAppointmentsView.as_view(), name='appointments_user'),
    path('mail-confirmation/<int:pk>/', ConfirmEmailView.as_view(), name='confirm_mail'),
    path('confirm/resend/', ResendConfirmationMail.as_view(), name='confirm_resend'),
]

final_project/final_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler403

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("snapvisite.urls", namespace='snapvisite')),
    path('account/', include("account.urls", namespace='account')),
    path('account/', include('django.contrib.auth.urls'))
]

"""Overriding 403 error with custom view."""
handler403 = 'account.views.custom_error_403'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

final_project/snapvisite/urls.py
from django.urls import path
from .views import *


app_name = "snapvisite"

urlpatterns = [
    path('', MainPageView.as_view(), name='home-page'),
    path('snapvisite/create-company/', CreateCompanyFirstStepView.as_view(), name='create_company_first_step'),
    path('snapvisite/company-panel/', CompanyPanelView.as_view(), name='company_panel'),
    path('snapvisite/your-company/<int:pk>/', YourCompanyView.as_view(), name='your_company'),
    path('snapvisite/change-company-name/<int:pk>/', EditCompanyNameView.as_view(), name='company_name_edit'),
    path('snapvisite/change-company-description/<int:pk>/', EditCompanyDescriptionView.as_view(),
         name='company_desc_edit'),
    path('snapvisite/change-company-photo/<int:pk>/', EditCompanyPhotoView.as_view(), name='company_photo_edit'),
    path('snapvisite/create-address-company/<int:company_id>/', CreateAddressView.as_view(),
         name='company_address_add'),
    path('snapvisite/update-address-company/<int:pk>/<int:company_id>/', UpdateAddressView.as_view(),
         name='company_update_address'),
    path('snapvisite/schedule-company/<int:company_id>/', ScheduleListView.as_view(), name='schedule_company'),
    path('snapvisite/schedule-update/<int:pk>/<int:company_id>/', ScheduleUpdateView.as_view(), name='schedule_update'),
    path('snapvisite/create-service-company/<int:company_id>/', CreateServiceView.as_view(), name='add_service'),
    path('snapvisite/company/contact/<int:pk>/', UpdateContactView.as_view(), name='contact_edit'),
    path('snapvisite/update-service-company/<int:pk>/<int:company_id>/', UpdateServiceView.as_view(),
         name='service_edit'),
    path('snapvisite/update-categories-company/<int:pk>/', EditCompanyCategoriesView.as_view(), name='categories_edit'),
    path('snapvisite/company-search/', CompanyListSearchView.as_view(), name='company_search'),
    path('snapvisite/company-detail/<int:pk>/', CompanyUserView.as_view(), name='company_detail'),
    path('snapvisite/create-company-day/<int:company_id>/', CreateCompanyDay.as_view(), name='create_company_day'),
    path('snapvisite/terminal/work-day-multiple/<int:company_id>/', CreateMultipleCompanyDayView.as_view(),
         name='multiple_company_day'),
    path('snapvisite/terminal/<int:pk>/', CompanyTerminalView.as_view(), name='company_terminal'),
    path('snapvisite/terminal/timeslot/<int:day_id>/', CreateSingleTimeSlotView.as_view(), name='single_timeslot'),
    path('snapvisite/terminal/timeslot-multiple/<int:day_id>/', CreateMultipleTimeSlotView.as_view(),
         name='multiple_timeslot'),
    path('snapvisite/terminal-user/<int:pk>/<int:service_id>/', UserTerminal.as_view(), name='user_terminal'),
    path('snapvisite/terminal-user/appointment/<int:service_id>/<int:timeslot_id>/', CreateAppointmentView.as_view(),
         name='create-appointment'),
    path('snapvisite/terminal/delete-work-day/<int:pk>/<int:company_id>/', DeleteCompanyDayView.as_view(),
         name='delete_company_day'),
    path('snapvisite/terminal/delete-timeslot/<int:pk>/<int:company_id>/', DeleteTimeSlotView.as_view(),
         name='delete_timeslot'),
    path('snapvisite/terminal/delete-service/<int:pk>/<int:company_id>/', DeleteServiceView.as_view(),
         name='delete_service'),
    path('snapvisite/company/send-mail/<int:company_id>/', SendMailToCompany.as_view(), name='send_mail'),
]

final_project/snapvisite/models.py
import uuid
from django.dispatch import receiver
from django.db.models.signals import post_save
from account.models import Profile
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


class Category(models.Model):
    category_name = models.CharField(max_length=40)
    photo = models.ImageField(blank=True, null=True, upload_to='category_image')

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return f'{self.category_name}'


def save_photo(instance, filename):
    filename = f'{uuid.uuid1()}_{filename}'
    return f'company_photos/{instance.company_name}_{instance.id}/{filename}'


class Company(models.Model):
    company_name = models.CharField(max_length=35)
    photo = models.ImageField(blank=True, null=True, upload_to=save_photo)
    description = models.TextField(blank=True, null=True, max_length=310)
    created_date = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(Profile, on_delete=models.PROTECT)
    category = models.ManyToManyField(Category)
    phone_number = PhoneNumberField(blank=True, null=True)
    email = models.EmailField(verbose_name='email', max_length=80, unique=True, blank=True, null=True)

    class Meta:
        verbose_name = 'company'
        verbose_name_plural = 'companies'

    def __str__(self):
        return f'{self.company_name}'


class Address(models.Model):
    city = models.CharField(max_length=50)
    postal_code = models.CharField(max_length=8)
    street_name = models.CharField(max_length=50)
    street_number = models.CharField(max_length=50)
    apartment_number = models.CharField(max_length=5, blank=True, null=True)
    company = models.OneToOneField(Company, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        verbose_name = 'address'
        verbose_name_plural = 'addresses'

    def __str__(self):
        return f'({self.city} {self.street_name} {self.street_number})'


class CompanyDay(models.Model):
    date = models.DateField()
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('company', 'date')
        verbose_name = 'companyday'
        verbose_name_plural = 'companydays'
        ordering = ('date',)

    def __str__(self):
        return f'({self.date})'


class Schedule(models.Model):
    DAYS = (('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'),
            ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'))
    day_of_week = models.CharField(max_length=50, choices=DAYS, null=True, blank=True)
    open_time = models.TimeField(null=True, blank=True, default=None)
    close_time = models.TimeField(null=True, blank=True, default=None)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'schedule'
        verbose_name_plural = 'schedules'

    def __str__(self):
        return f'{self.company} {self.day_of_week}'


@receiver(post_save, sender=Company)
def company_created_add_schedule(sender, instance, created, *args, **kwargs):
    if created:
        for schedule_day in range(len(Schedule.DAYS)):
            Schedule.objects.create(day_of_week=Schedule.DAYS[schedule_day][0], company=instance)


class Service(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField()
    time = models.IntegerField(default=30,
                               help_text="Put time in minutes. Like '60' = 1h, '30' = 30min, '90' = 1h 30min")
    price = models.DecimalField(max_digits=6, decimal_places=2)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'service'
        verbose_name_plural = 'services'

    def __str__(self):
        return f'{self.name} {self.company.company_name}'


class TimeSlot(models.Model):
    start_time = models.TimeField()
    status = models.BooleanField(default=True)
    company_day = models.ForeignKey(CompanyDay, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'timeslot'
        verbose_name_plural = 'timeslots'
        ordering = ('start_time',)

    def __str__(self):
        return f'({self.company_day.company.company_name};\
         {self.company_day.date}[Available: {self.status} Id: {self.pk}]; ({self.start_time}))'


class Appointment(models.Model):
    note = models.CharField(max_length=128, null=True, blank=True)
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    time_slot = models.OneToOneField(TimeSlot, on_delete=models.CASCADE)
    payment_status = models.BooleanField(default=False,
                                         choices=[(True, 'Pay with card now'), (False, 'Pay by cash on visit')])
    appointment_code = models.CharField(max_length=50, default="123")

    class Meta:
        verbose_name = 'appointment'
        verbose_name_plural = 'appointments'

    def __str__(self):
        return f'(Id: {self.pk} {self.user.email}-{self.service.name}' \
               f' [{self.time_slot.start_time}])'

    def create_appointment_code(self):
        return f'{self.user.pk}{self.service.company.company_name[:3]}{uuid.uuid1()}'

final_project/snapvisite/templates/snapvisite/company_list.html
{% extends 'snapvisite/base.html' %}
{% load static %}
{% load custom_tags %}

{% block content %}

{{ category }}
<div class="container" style="font-family: 'Lato Light', serif;">
        {% for company in company_list %}
        {% include "snapvisite/company_row.html" %}
        {% endfor %}
</div>



{% endblock content %}

final_project/snapvisite/templates/snapvisite/company_row.html
{% load static %}
{% load custom_tags %}
    <div class="row mt-3 bg-light" style="border: 1px solid lightgray; height: 340px">
        <div class="col-3" style="height: 300px">
            {% if company.photo %}
            <a href="{% url 'snapvisite:company_detail' company.pk %}"><img class="pt-3" src="{{ company.photo.url }}" style="height: 98%; width: 98%;"></a>
            {% else %}
            <a href="{% url 'snapvisite:company_detail' company.pk %}"><img class="shadow-sm bg-light mt-3" src="{% static 'snapvisite/images/default_company_photo.png' %}" style="height: 98%; width: 98%;"></a>
            {% endif %}
        </div>
        <div class="col-3">
            <p style="font-size: 36px;"> {{ company.company_name }} </p>
            <p style="font-size: 28px;"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-signpost-2" viewBox="0 0 16 16">
            <path d="M7 1.414V2H2a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h5v1H2.5a1 1 0 0 0-.8.4L.725 8.7a.5.5 0 0 0 0 .6l.975 1.3a1 1 0 0 0 .8.4H7v5h2v-5h5a1 1 0 0 0 1-1V8a1 1 0 0 0-1-1H9V6h4.5a1 1 0 0 0 .8-.4l.975-1.3a.5.5 0 0 0 0-.6L14.3 2.4a1 1 0 0 0-.8-.4H9v-.586a1 1 0 0 0-2 0zM13.5 3l.75 1-.75 1H2V3h11.5zm.5 5v2H2.5l-.75-1 .75-1H14z"/>
            </svg> Address </p>
            {% if company.address.apartment_number %}
            <p style="font-size: 22px">{{ company.address.street_name }} {{ company.address.street_number }} / {{ company.address.apartment_number }}</p>
            {% else %}
            <p style="font-size: 22px">{{ company.address.street_name }} {{ company.address.street_number }}</p>
            {% endif %}
            <p style="font-size: 22px">{{ company.address.city }}, {{ company.address.postal_code }}</p>
            <a href="{% url 'snapvisite:company_detail' company.pk %}"><button type="button" style="width:100%" class="btn btn-light btn-outline-dark btn-sm">Visit company site</button></a>
        </div>
        <div class="col-3 ps-5">
            <p style="font-size: 28px; margin-right: 15px;"><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-clock" viewBox="0 0 16 16">
            <path d="M8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z"/>
            <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm7-8A7 7 0 1 1 1 8a7 7 0 0 1 14 0z"/>
            </svg> Open hours: </p>
            {% for schedule in company.schedule_set.all %}
            {% if schedule.open_time and schedule.close_time %}
            <p> <strong>{{ schedule.day_of_week }}</strong> {{ schedule.open_time|time:"H:i"}}-{{ schedule.close_time|time:"H:i" }} </p>
            {% else %}
            <p> <strong>{{ schedule.day_of_week }}</strong> Closed </p>
            {% endif %}
            {% endfor %}
        </div>
        <div class="col-3 pt-3">
            {% for service in company.service_set.all %}
            {% if forloop.counter <= 3 %}
            <p data-bs-toggle="popover" data-bs-content="{{ service.description }}" data-bs-trigger="hover" ><strong>{{ service.name }} -</strong> {{ service.price }}.- {{ service.time|duration_format }}</p>
            <a href="{% url 'snapvisite:user_terminal' company.id service.id %}">
                <button type="button" style="width:100%" class="btn btn-light btn-outline-success">Snap your visit</button>
            </a>
            {% if forloop.counter <= 2 %}
            <hr>
            {% endif %}
            {% endif %}
            {% endfor %}
        </div>
    </div>

final_project/snapvisite/templates/snapvisite/nav_bar_your_company.html
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container">
    <a class="navbar-brand">
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
      <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
      <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
      </svg> Editor</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'snapvisite:company_name_edit' object.id %}">Company name</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'snapvisite:company_desc_edit' object.id %}">Description</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'snapvisite:company_photo_edit' object.id %}">Photo</a>
        </li>
        {% if object.address %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'snapvisite:company_update_address' object.address.id object.id %}">Address</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'snapvisite:company_address_add' object.id %}">Address</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'snapvisite:schedule_company' object.id %}">Schedule</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'snapvisite:add_service' object.id %}"> Add Service</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'snapvisite:contact_edit' object.id %}"> Contact</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'snapvisite:categories_edit' object.id %}">Categories</a>
        </li>
      </ul>
    </div>
    <a class="navbar-brand"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-calendar-week" viewBox="0 0 16 16">
    <path d="M11 6.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm-3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm-5 3a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1z"/>
    <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
    </svg> Calendar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'snapvisite:company_terminal' object.id %}">Terminal</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

final_project/snapvisite/templates/snapvisite/terminal.html
{% extends 'snapvisite/base.html' %}
{% load static %}
{% load custom_tags %}



{% block content %}

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <div class="container-fluid">
        <a class="navbar-brand"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-calendar-week" viewBox="0 0 16 16">
        <path d="M11 6.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm-3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm-5 3a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1z"/>
        <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
        </svg> Calendar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'snapvisite:multiple_company_day' object.id %}">Open your worktime</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'snapvisite:create_company_day' object.id %}">Open single day</a>
              </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container-fluid text-center pt-3" style="font-family: 'Lato Light', serif;">
    <div class="row row-cols-7">

        <nav aria-label="Page navigation">
            <ul class="pagination">
                {% if days.has_previous %}
                <li class="page-item"><a style="color: inherit;text-decoration: inherit;" class="page-link" href="?page=1">&laquo First</a></li>
                <li class="page-item"><a style="color: inherit;text-decoration: inherit;" class="page-link" href="?page={{ days.previous_page_number }}"> Previous </a></li>
                {% endif %}
                <li class="page-item disabled"><a class="page-link" href="#">Page: {{ days.number }} of {{ days.paginator.num_pages }}</a></li>
                {% if days.has_next %}
                <li class="page-item"><a style="color: inherit;text-decoration: inherit;" class="page-link" href="?page={{ days.next_page_number }}">Next</a></li>
                <li class="page-item"><a style="color: inherit;text-decoration: inherit;" class="page-link" href="?page={{ days.paginator.num_pages }}">Last &raquo</a></li>
                {% endif %}
            </ul>
        </nav>
    {% for company_day in days %}
        <div class="col" style="max-width: calc(100% / 7)">
            <a href="{% url 'snapvisite:delete_company_day' company_day.id object.id %}"><button style="width: 3px; height: 3px" type="button" class="btn-close" aria-label="Close"></button></a>
            <h3>{{  company_day.date|date:"d-m-Y" }}</h3>
            <h4>{{  company_day.date|date:"l" }}</h4>
            {% for timeslot in company_day.timeslot_set.all %}
            <div class="list-group">

                <!-- FREE TIMESLOT -->
                {% if timeslot.status %}

                <button type="button" class="list-group-item list-group-item-action list-group-item-success" data-bs-toggle="modal" data-bs-target="#modal_delete{{ timeslot.id }}">
                    {{ timeslot.start_time|time:"H:i" }}
                </button>


                <div class="modal fade" id="modal_delete{{ timeslot.id }}" tabindex="-1" aria-labelledby="descriptionLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h2 class="modal-title" id="descriptionLabel" style="text-align: start">
                                    <strong>{{ timeslot.company_day.date|date:"l" }} - {{ timeslot.start_time|time:"H:i" }}</strong></h2>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="close"></button>
                            </div>

                            <div class="modal-body" style="text-align: start">
                                <a href="{% url 'snapvisite:delete_timeslot' timeslot.id object.id %}"><button  type="button" class="btn btn-danger" aria-label="Close">Delete Timeslot</button></a>
                            </div>
                        </div>
                    </div>
                </div>


                <!-- OCCUPIED TIMESLOT -->
                {% else %}

                <button type="button" class="list-group-item list-group-item-action list-group-item-primary" data-bs-toggle="modal" data-bs-target="#modal{{ timeslot.appointment.id }}">
                    {{ timeslot.start_time|time:"H:i" }}
                </button>
                <div class="modal fade" id="modal{{ timeslot.appointment.id }}" tabindex="-1" aria-labelledby="descriptionLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h2 class="modal-title" id="descriptionLabel" style="text-align: start">
                                    <strong>{{ timeslot.company_day.date|date:"l" }} - {{ timeslot.start_time|time:"H:i" }}</strong></h2>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="close"></button>
                            </div>

                            <div class="modal-body" style="text-align: start">
                                <h4><strong>Service:</strong> {{ timeslot.appointment.service.name }}</h4>
                                <h4><strong>Client:</strong> {{ timeslot.appointment.user.first_name }} {{ timeslot.appointment.user.last_name }}</h4>
                                <h4><strong>Phone number:</strong> {{ timeslot.appointment.user.phone_number }}</h4>
                                <h4><strong>Additional information:</strong>
                                    <textarea disabled rows="5" style="font-size: 20px; width: 100%">{{ timeslot.appointment.note }}</textarea>
                                </h4>
                                {% if timeslot.appointment.payment_status %}
                                <h2 style="margin-top: 30px; border-top: solid 1px black; padding-top: 20px">Payment status: <span class="badge bg-success">Paid</span> </h2>
                                {% else %}
                                <h2 style="margin-top: 30px ;border-top: solid 1px black; padding-top: 20px">Payment status: <span class="badge bg-danger">Not paid</span></h2>
                                {% endif %}
                                <div class="text" style="border-top: solid 1px black; padding-top: 15px">Appointment code:<br> {{ timeslot.appointment.appointment_code }}</div>

                            </div>
                        </div>
                    </div>
                </div>

                {% endif %}
            </div>
            {% endfor %}
            <br>
            <div class="dropdown">
                <button style="width:100%" class="btn btn-success dropdown-toggle" type="button" id="dropdown{{ company_day.id }}" data-bs-toggle="dropdown" aria-expanded="false">Create TimeSlot
                </button>
                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdown{{ company_day.id }}">
                    <li><a class="dropdown-item" href="{% url 'snapvisite:multiple_timeslot' company_day.id %}">Multiple</a></li>
                    <li><a class="dropdown-item" href="{% url 'snapvisite:single_timeslot' company_day.id %}">Single</a></li>
                </ul>
            </div>
        </div>
    {% endfor %}
    </div>
</div>

<script>
$( document ).ready(function() {
    $(function(){
        $('.timepicker').timepicker({
            timeFormat: 'HH:mm ',
            interval: 30,
            minTime: '6am',
            maxTime: '23:30pm',
            startTime: '6:00',
            dynamic: false,
            dropdown: true,
            scrollbar: true
        });
    });
});

</script>


{% endblock content %}